Implement dateadd macro DNA-15944 [DNA-20679]
UiPath/ProcessMining-pm-utils pull request #80
Opened 2023-11-14 11:10 UTC by silviustanimir

## Description
- Implement charindex macro for Spark compatbility.

## Release
- [x] Direct release (`main`)
- [ ] Merge to `dev` (or other) branch
  - Why:

### Did you consider?
- [x] Does it Work on Automation Suite / SQL Server
- [x] Does it Work on Automation Cloud / Snowflake
- [ ] ~~What is the performance impact?~~
- [ ] ~~The version number in `dbt_project.yml`~~

2023-11-16 07:51 UTC, Dennis-UiPath requested changes

2023-11-16 07:51 UTC, Dennis-UiPath commented on README.md
> +This macro adds a specified number value (as a signed integer) to a specified datepart of an input date value, and then returns that modified value. The datepart can be any of the following values fo
We are expecting a date or a datetime as input for this function, right? Can this be mentioned here explicitly. Now it states "input date value" and in the example uses "expression" (which can be a string)

2023-11-16 07:51 UTC, Dennis-UiPath commented on macros/multiple_databases/dateadd.sql
> +    dateadd({{ datepart }}, {{ number }}, try_to_timestamp(to_varchar({{ datetime_field }})))
If we know the datetime_field is a date or a datetime, we can use to_timestamp({{datetime_field}})

2023-11-16 07:51 UTC, Dennis-UiPath commented on macros/multiple_databases/dateadd.sql
> +    {%- set clock_component -%}
can we rename this value to time_value? It represents the time only part of the datetime

2023-11-16 07:51 UTC, Dennis-UiPath commented on macros/multiple_databases/dateadd.sql
> +        to_unix_timestamp({{ datetime_field }}) - to_unix_timestamp(date_trunc('DD', {{ datetime_field }}))
If we convert the input value using to_unix_timestamp, we will lose the millisecond precision. This makes it different from the Snowflake and SQL Server implementations

2023-11-17 06:45 UTC, silviustanimir commented on README.md
> +This macro adds a specified number value (as a signed integer) to a specified datepart of an input date or datetime, and then returns that modified value. The datepart can be any of the following val
Actually there are more for [SQL Server](https://learn.microsoft.com/en-us/sql/t-sql/functions/dateadd-transact-sql?view=sql-server-ver16), but I will remove the second list.

2023-11-17 08:42 UTC, Dennis-UiPath approved these changes

2023-11-17 08:46 UTC, merged